# Generated by Django 5.2.1 on 2025-06-02 04:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва категорії')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Слаг')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата створення')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва продукту')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Слаг')),
                ('price', models.FloatField(verbose_name='Ціна')),
                ('product_qty', models.IntegerField(verbose_name='Кількість товару')),
                ('reviews_qty', models.IntegerField(verbose_name='Кількість відгуків')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукти',
                'ordering': ['-created_at'],
            },
        ),
    ]
